apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_JOB_NAME
  labels:
    app: k8-flagstat
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: VAR_JOB_NAME
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          args: ["INPUT", "OUTPUT"]
          resources:
            requests:
              memory: "8Gi"
            limits:
              memory: "8Gi"
      restartPolicy: Never
